#!/bin/sh

src=src
out=BP/scripts
pack="catalyst_$(
		cat "BP/manifest.json" |
		sed -n '0,/.*"version": "\(.*\)".*/s//\1/p'
	).mcaddon"

# some cleanup
mkdir -p "$out"
rm -rf "$out"/*

# run typescript
npx tsc

# copy additional files
for file in $( find "$src" -type f ! -name "*.[jt]s" ) ; do
	dest="$out${file#"$src"}"
	mkdir -p "$( dirname "$dest" )"
	cp "$file" "$dest"
done

# package add-on
rm "$pack"
zip -r "$pack" 'BP' 'RP' 'LICENSE' 'README.md'
