/**
 * glyph emojis
 * see: <vanilla_resource_pack>/font/glyph_E0.png <and> glyph_E1.png
 * reference: https://wiki.bedrock.dev/concepts/emojis.html
 */

// lt = left trigger
// rt = right trigger
// lb = left bumper
// rb = right bumper
// ls = left stick
// rs = right stick
// lg = left grab
// rg = right grab

export const glyphs: Record<string, string> = {
	xbox_a: "\uE000",
	xbox_b: "\uE001",
	xbox_x: "\uE002",
	xbox_y: "\uE003",
	xbox_lb: "\uE004",
	xbox_rb: "\uE005",
	xbox_lt: "\uE006",
	xbox_rt: "\uE007",
	xbox_back: "\uE008",
	xbox_start: "\uE009",
	xbox_ls: "\uE00A",
	xbox_rs: "\uE00B",
	xbox_dpad_up: "\uE00C",
	xbox_dpad_left: "\uE00D",
	xbox_dpad_down: "\uE00E",
	xbox_dpad_right: "\uE00F",
	xbox_a_light: "\uE010",
	xbox_b_light: "\uE011",
	xbox_x_light: "\uE012",
	xbox_y_light: "\uE013",
	touch_new_jump: "\uE014",
	touch_new_attack: "\uE015",
	touch_new_joystick: "\uE016",
	crosshair: "\uE017",
	touch_new_place: "\uE018",
	touch_new_sneak: "\uE019",
	touch_new_sprint: "\uE01A",
	touch_new_flyup: "\uE01B",
	touch_new_flydown: "\uE01C",
	touch_new_dismount: "\uE01D",
	playstation_cross: "\uE020",
	playstation_circle: "\uE021",
	playstation_square: "\uE022",
	playstation_triangle: "\uE023",
	playstation_l1: "\uE024", // lb
	playstation_r1: "\uE025", // rb
	playstation_l2: "\uE026", // lt
	playstation_r2: "\uE027", // rt
	playstation_touchpad: "\uE028",
	playstation_options: "\uE029",
	playstation_l3: "\uE02A", // ls
	playstation_r3: "\uE02B", // rs
	playstation_dpad_up: "\uE02C",
	playstation_dpad_left: "\uE02D",
	playstation_dpad_down: "\uE02E",
	playstation_dpad_right: "\uE02F",
	switch_a: "\uE040",
	switch_b: "\uE041",
	switch_x: "\uE042",
	switch_y: "\uE043",
	switch_l: "\uE044", // lb
	switch_r: "\uE045", // rb
	switch_zl: "\uE046", // lt
	switch_zr: "\uE047", // rt
	switch_minus: "\uE048",
	switch_plus: "\uE049",
	switch_ls: "\uE04A",
	switch_rs: "\uE04B",
	switch_dpad_up: "\uE04C",
	switch_dpad_left: "\uE04D",
	switch_dpad_down: "\uE04E",
	switch_dpad_right: "\uE04F",
	mouse_left_click: "\uE060",
	mouse_right_click: "\uE061",
	mouse_middle_click: "\uE062",
	mouse: "\uE063",
	touch_up_small: "\uE065",
	touch_left_small: "\uE066",
	touch_down_small: "\uE067",
	touch_right_small: "\uE068",
	touch_jump_small: "\uE069",
	touch_crouch_small: "\uE06A",
	touch_inventory_small: "\uE06B",
	touch_flyup_small: "\uE06C",
	touch_flydown_small: "\uE06D",
	xbox_lt_small: "\uE06E",
	xbox_rt_small: "\uE06F",
	mouse_left_click_small: "\uE070",
	mouse_right_click_small: "\uE071",
	mouse_middle_click_small: "\uE072",
	mouse_small: "\uE073",
	xbox_ls_small: "\uE075",
	xbox_rs_small: "\uE076",
	touch_up: "\uE080",
	touch_left: "\uE081",
	touch_down: "\uE082",
	touch_right: "\uE083",
	touch_jump: "\uE084",
	touch_crouch: "\uE085",
	touch_flyup: "\uE086",
	touch_flydown: "\uE087",
	touch_fly_stop: "\uE088",
	craft_toggle_on: "\uE0A0",
	craft_toggle_off: "\uE0A1",
	windowsmr_lg: "\uE0C0",
	windowsmr_rg: "\uE0C1",
	windowsmr_menu: "\uE0C2",
	windowsmr_ls: "\uE0C3",
	windowsmr_rs: "\uE0C4",
	windowsmr_lpad: "\uE0C5", // left touch pad
	windowsmr_lpad_horizontal: "\uE0C6",
	windowsmr_lpad_vertical: "\uE0C7",
	windowsmr_rpad: "\uE0C8", // right touch pad
	windowsmr_rpad_horizontal: "\uE0C9",
	windowsmr_rpad_vertical: "\uE0CA",
	windowsmr_lt: "\uE0CB",
	windowsmr_rt: "\uE0CC",
	windowsmr_windows: "\uE0CD",
	oculus_0: "\uE0E0",
	oculus_a: "\uE0E1",
	oculus_b: "\uE0E2",
	oculus_lg: "\uE0E3",
	oculus_rg: "\uE0E4",
	oculus_ls: "\uE0E5",
	oculus_rs: "\uE0E6",
	oculus_lt: "\uE0E7",
	oculus_rt: "\uE0E8",
	oculus_x: "\uE0E9",
	oculus_y: "\uE0EA",
	food: "\uE100",
	armor: "\uE101",
	minecoin: "\uE102",
	agent: "\uE103",
	immersive_reader: "\uE104",
	token: "\uE105",
	hollow_star: "\uE106",
	solid_star: "\uE107",
	wooden_pickaxe: "\uE108",
	wooden_sword: "\uE109",
	crafting_table: "\uE10A",
	furnace: "\uE10B",
	heart: "\uE10C",

	// custom glyphs
	board: "\uE10D",
	monitor: "\uE10E",
	barrier: "\uE10F",
	check: "\uE110",
	x: "\uE111",
	plus: "\uE112",
	minus: "\uE113",
	key: "\uE114",
	file: "\uE115",
	folder: "\uE116",
	code: "\uE117",
};
