name: "CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm install

    - name: Build add-on
      run: sh ./build

    - name: Get the package name
      id: name
      run: |
        VERSION=$(node -p "require('./BP/manifest.json').header.version")
        echo "::set-output name=output_file::catalyst_${VERSION}.mcaddon"

    - name: Archive generated files
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.name.outputs.output_file }}
        path: ${{ steps.name.outputs.output_file }}
